### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: FormData is not defined

### ISSUE THREAD

**Issue by gelnuro** [therealparmesh/object-to-formdata#42] opened 2019-08-27 11:49 UTC
When I use it in code

```
    const d = {
      from: 'HQ',
      recipients_is_delayed: [
        {
          address: 'someAddress',
          name: 'some name',
        },
      ],
      recipients: [
        {
          address: 'someAddress',
          name: 'some name',
        },
      ],
      blind_copies: [
        {
          address: 'someAddress',
          name: 'some name',
        },
      ],
      subject: `Анонимный отзыв`,
      body: `тут текст`,
    };
    
    const formData = objectToFormData(d);
    
    callApiFetch(
      {
        url: `https://someUrl`,
        body: formData,
      },
      false,
    );
```
returns ReferenceError: FormData is not defined at isFormData (/path/node_modules/object-to-formdata/index.js:42:27)

adding line on top of the /object-to-formdata/index.js file
`const FormData = require('form-data');`
solved problem.

**Comment by therealparmesh** [comment] 2019-09-01 23:31
You need to polyfill this for it to work. I am thinking about adding a configuration option for you to provide your own `FormData` constructor.

**Comment by therealparmesh** [comment] 2019-09-01 23:32
This is essentially a duplicate of https://github.com/therealparmesh/object-to-formdata/issues/27. Let's move the discussion there.

**Closed by therealparmesh** 2019-09-01 23:32 UTC
